services:
  - type: web
    name: awap-next-app
    env: node
    plan: free
    buildCommand: "npm install --include=dev && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_VERSION
        value: "18"
